from .kling import OPERATIONS as KLING_OPERATIONS
from .minimax import OPERATIONS as MINIMAX_OPERATIONS
from .partners import OPERATIONS as PARTNER_OPERATIONS
from .seedance import OPERATIONS as SEEDANCE_OPERATIONS
from .unified import OPERATIONS as UNIFIED_OPERATIONS
from .vidu import OPERATIONS as VIDU_OPERATIONS
from .wan import OPERATIONS as WAN_OPERATIONS

OPERATIONS = (
    *UNIFIED_OPERATIONS,
    *WAN_OPERATIONS,
    *KLING_OPERATIONS,
    *MINIMAX_OPERATIONS,
    *VIDU_OPERATIONS,
    *SEEDANCE_OPERATIONS,
    *PARTNER_OPERATIONS,
)
