from __future__ import annotations

from ...specs import operation

OPERATIONS = (
    operation(
        group="video",
        family="wan",
        name="wan-2.5-i2v-preview",
        title="Wan 2.5 Preview 图生视频",
        method="POST",
        base="v3",
        path="/async/wan-2.5-i2v-preview",
        doc_slug="reference-wan-2.5-i2v-preview",
    ),
    operation(
        group="video",
        family="wan",
        name="wan-2.5-t2v-preview",
        title="Wan 2.5 Preview 文生视频",
        method="POST",
        base="v3",
        path="/async/wan-2.5-t2v-preview",
        doc_slug="reference-wan-2.5-t2v-preview",
    ),
    operation(
        group="video",
        family="wan",
        name="wan-i2v",
        title="Wan 2.1 图生视频",
        method="POST",
        base="v3",
        path="/async/wan-i2v",
        doc_slug="reference-wan-i2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan-t2v",
        title="Wan 2.1 文生视频",
        method="POST",
        base="v3",
        path="/async/wan-t2v",
        doc_slug="reference-wan-t2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan2.2-i2v",
        title="Wan 2.2 图生视频",
        method="POST",
        base="v3",
        path="/async/wan-2.2-i2v",
        doc_slug="reference-wan2.2-i2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan2.2-t2v",
        title="Wan 2.2 文生视频",
        method="POST",
        base="v3",
        path="/async/wan-2.2-t2v",
        doc_slug="reference-wan2.2-t2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan2.6-i2v",
        title="Wan 2.6 图生视频",
        method="POST",
        base="v3",
        path="/async/wan2.6-i2v",
        doc_slug="reference-wan2.6-i2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan2.6-t2v",
        title="Wan 2.6 文生视频",
        method="POST",
        base="v3",
        path="/async/wan2.6-t2v",
        doc_slug="reference-wan2.6-t2v",
    ),
    operation(
        group="video",
        family="wan",
        name="wan2.6-v2v",
        title="Wan 2.6 参考生视频",
        method="POST",
        base="v3",
        path="/async/wan2.6-v2v",
        doc_slug="reference-wan2.6-v2v",
    ),
)
