from .jimeng import OPERATIONS as JIMENG_OPERATIONS
from .partners import OPERATIONS as PARTNER_OPERATIONS
from .qwen import OPERATIONS as QWEN_OPERATIONS
from .seedream import OPERATIONS as SEEDREAM_OPERATIONS
from .tools import OPERATIONS as TOOL_OPERATIONS
from .z_image import OPERATIONS as Z_IMAGE_OPERATIONS

OPERATIONS = (
    *SEEDREAM_OPERATIONS,
    *JIMENG_OPERATIONS,
    *QWEN_OPERATIONS,
    *TOOL_OPERATIONS,
    *PARTNER_OPERATIONS,
    *Z_IMAGE_OPERATIONS,
)
