from .base import OPERATIONS as BASE_OPERATIONS
from .batch import OPERATIONS as BATCH_OPERATIONS
from .llm import OPERATIONS as LLM_OPERATIONS
from .search import OPERATIONS as SEARCH_OPERATIONS
from .tasks import OPERATIONS as TASK_OPERATIONS
from .image import OPERATIONS as IMAGE_OPERATIONS
from .video import OPERATIONS as VIDEO_OPERATIONS
from .audio import OPERATIONS as AUDIO_OPERATIONS

OPERATIONS = (
    *BASE_OPERATIONS,
    *LLM_OPERATIONS,
    *BATCH_OPERATIONS,
    *IMAGE_OPERATIONS,
    *VIDEO_OPERATIONS,
    *AUDIO_OPERATIONS,
    *SEARCH_OPERATIONS,
    *TASK_OPERATIONS,
)
